"""add teacher alf sessions

Revision ID: 1c7d57c6cc53
Revises: 577a6af92858
Create Date: 2026-10-01 14:23:31.462689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7d57c6cc53'
down_revision: Union[str, Sequence[str], None] = '577a6af92858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_expense_categories_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories'))
    )
    op.create_index(op.f('ix_expense_categories_school_id'), 'expense_categories', ['school_id'], unique=False)
    op.create_table('fee_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_fee_categories_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_categories'))
    )
    op.create_index(op.f('ix_fee_categories_school_id'), 'fee_categories', ['school_id'], unique=False)
    op.create_table('expenses',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id_expense_categories')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_expenses_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_reference'), 'expenses', ['reference'], unique=False)
    op.create_index(op.f('ix_expenses_school_id'), 'expenses', ['school_id'], unique=False)
    op.create_table('student_fees',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('fee_category_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], name=op.f('fk_student_fees_fee_category_id_fee_categories')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_student_fees_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_student_fees_session_id_academic_sessions')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('fk_student_fees_student_id_student_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_student_fees_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_fees')),
    sa.UniqueConstraint('student_id', 'fee_category_id', 'session_id', 'term_id', name='uq_student_fee_period')
    )
    op.create_index(op.f('ix_student_fees_fee_category_id'), 'student_fees', ['fee_category_id'], unique=False)
    op.create_index(op.f('ix_student_fees_school_id'), 'student_fees', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_fees_session_id'), 'student_fees', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_fees_student_id'), 'student_fees', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_fees_term_id'), 'student_fees', ['term_id'], unique=False)
    op.create_table('teacher_alf_sessions',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='alf_session_status'), nullable=False),
    sa.Column('independent_reading_completed', sa.Boolean(), nullable=False),
    sa.Column('mini_lesson_completed', sa.Boolean(), nullable=False),
    sa.Column('case_study_completed', sa.Boolean(), nullable=False),
    sa.Column('project_based_learning_completed', sa.Boolean(), nullable=False),
    sa.Column('evaluation_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_teacher_alf_sessions_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_teacher_alf_sessions_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_alf_sessions_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_alf_sessions'))
    )
    op.create_index(op.f('ix_teacher_alf_sessions_class_id'), 'teacher_alf_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_alf_sessions_lesson_id'), 'teacher_alf_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_teacher_alf_sessions_teacher_id'), 'teacher_alf_sessions', ['teacher_id'], unique=False)
    op.create_table('payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_fee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_payments_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], name=op.f('fk_payments_student_fee_id_student_fees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('fk_payments_student_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_school_id'), 'payments', ['school_id'], unique=False)
    op.create_index(op.f('ix_payments_student_fee_id'), 'payments', ['student_fee_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_student_fee_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_school_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_teacher_alf_sessions_teacher_id'), table_name='teacher_alf_sessions')
    op.drop_index(op.f('ix_teacher_alf_sessions_lesson_id'), table_name='teacher_alf_sessions')
    op.drop_index(op.f('ix_teacher_alf_sessions_class_id'), table_name='teacher_alf_sessions')
    op.drop_table('teacher_alf_sessions')
    op.drop_index(op.f('ix_student_fees_term_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_student_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_session_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_school_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_fee_category_id'), table_name='student_fees')
    op.drop_table('student_fees')
    op.drop_index(op.f('ix_expenses_school_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_reference'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_fee_categories_school_id'), table_name='fee_categories')
    op.drop_table('fee_categories')
    op.drop_index(op.f('ix_expense_categories_school_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
