"""add marketplace cart checkout payment

Revision ID: 1fd43523828b
Revises: 706d3ef1acd5
Create Date: 2026-09-22 08:50:06.343965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd43523828b'
down_revision: Union[str, Sequence[str], None] = '706d3ef1acd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_carts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_marketplace_carts_customer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_carts'))
    )
    op.create_index(op.f('ix_marketplace_carts_customer_id'), 'marketplace_carts', ['customer_id'], unique=True)
    op.create_table('marketplace_checkouts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('checkout_number', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='checkout_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_marketplace_checkouts_customer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_checkouts'))
    )
    op.create_index(op.f('ix_marketplace_checkouts_checkout_number'), 'marketplace_checkouts', ['checkout_number'], unique=True)
    op.create_index(op.f('ix_marketplace_checkouts_customer_id'), 'marketplace_checkouts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_marketplace_checkouts_status'), 'marketplace_checkouts', ['status'], unique=False)
    op.create_table('marketplace_orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vendor_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID_HELD', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('delivery_confirmed', sa.Boolean(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['marketplace_checkouts.id'], name=op.f('fk_marketplace_orders_checkout_id_marketplace_checkouts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_marketplace_orders_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketplace_vendors.id'], name=op.f('fk_marketplace_orders_vendor_id_marketplace_vendors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_marketplace_orders_order_number'))
    )
    op.create_index(op.f('ix_marketplace_orders_checkout_id'), 'marketplace_orders', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_customer_id'), 'marketplace_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_vendor_id'), 'marketplace_orders', ['vendor_id'], unique=False)
    op.create_table('marketplace_payments',
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('access_code', sa.String(length=255), nullable=True),
    sa.Column('authorization_url', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('paystack_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('authorization_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['marketplace_checkouts.id'], name=op.f('fk_marketplace_payments_checkout_id_marketplace_checkouts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_payments'))
    )
    op.create_index(op.f('ix_marketplace_payments_checkout_id'), 'marketplace_payments', ['checkout_id'], unique=True)
    op.create_index(op.f('ix_marketplace_payments_reference'), 'marketplace_payments', ['reference'], unique=True)
    op.create_index(op.f('ix_marketplace_payments_status'), 'marketplace_payments', ['status'], unique=False)
    op.create_table('marketplace_payouts',
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bank_code', sa.String(length=20), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('recipient_code', sa.String(length=255), nullable=True),
    sa.Column('transfer_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='payoutstatus'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketplace_vendors.id'], name=op.f('fk_marketplace_payouts_vendor_id_marketplace_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_payouts'))
    )
    op.create_table('marketplace_vendor_bank_accounts',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('recipient_code', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketplace_vendors.id'], name=op.f('fk_marketplace_vendor_bank_accounts_vendor_id_marketplace_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_vendor_bank_accounts'))
    )
    op.create_table('marketplace_wallets',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pending_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketplace_vendors.id'], name=op.f('fk_marketplace_wallets_vendor_id_marketplace_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_wallets'))
    )
    op.create_index(op.f('ix_marketplace_wallets_vendor_id'), 'marketplace_wallets', ['vendor_id'], unique=True)
    op.create_table('marketplace_cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], name=op.f('fk_marketplace_cart_items_cart_id_marketplace_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_marketplace_cart_items_listing_id_marketplace_listings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_cart_items')),
    sa.UniqueConstraint('cart_id', 'listing_id', name='uq_marketplace_cart_listing')
    )
    op.create_index(op.f('ix_marketplace_cart_items_cart_id'), 'marketplace_cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_items_listing_id'), 'marketplace_cart_items', ['listing_id'], unique=False)
    op.create_table('marketplace_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_marketplace_order_items_listing_id_marketplace_listings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], name=op.f('fk_marketplace_order_items_order_id_marketplace_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_order_items'))
    )
    op.create_index(op.f('ix_marketplace_order_items_listing_id'), 'marketplace_order_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_marketplace_order_items_order_id'), 'marketplace_order_items', ['order_id'], unique=False)
    op.drop_index(op.f('uq_class_templates_name_level'), table_name='class_templates')
    op.drop_constraint(op.f('uq_class_templates_template_name_level'), 'class_templates', type_='unique')
    op.drop_constraint(op.f('uq_subject_templates_name_level'), 'subject_templates', type_='unique')
    op.drop_constraint(op.f('uq_subjects_school_template_subject'), 'subjects', type_='unique')
    op.drop_constraint(op.f('uq_template_class_subjects_class_subject'), 'template_class_subjects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_template_class_subjects_class_subject'), 'template_class_subjects', ['class_template_id', 'subject_template_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_subjects_school_template_subject'), 'subjects', ['school_id', 'template_subject_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_subject_templates_name_level'), 'subject_templates', ['name', 'level'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_class_templates_template_name_level'), 'class_templates', ['academic_template_id', 'name', 'level'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_class_templates_name_level'), 'class_templates', ['name', 'level'], unique=True)
    op.drop_index(op.f('ix_marketplace_order_items_order_id'), table_name='marketplace_order_items')
    op.drop_index(op.f('ix_marketplace_order_items_listing_id'), table_name='marketplace_order_items')
    op.drop_table('marketplace_order_items')
    op.drop_index(op.f('ix_marketplace_cart_items_listing_id'), table_name='marketplace_cart_items')
    op.drop_index(op.f('ix_marketplace_cart_items_cart_id'), table_name='marketplace_cart_items')
    op.drop_table('marketplace_cart_items')
    op.drop_index(op.f('ix_marketplace_wallets_vendor_id'), table_name='marketplace_wallets')
    op.drop_table('marketplace_wallets')
    op.drop_table('marketplace_vendor_bank_accounts')
    op.drop_table('marketplace_payouts')
    op.drop_index(op.f('ix_marketplace_payments_status'), table_name='marketplace_payments')
    op.drop_index(op.f('ix_marketplace_payments_reference'), table_name='marketplace_payments')
    op.drop_index(op.f('ix_marketplace_payments_checkout_id'), table_name='marketplace_payments')
    op.drop_table('marketplace_payments')
    op.drop_index(op.f('ix_marketplace_orders_vendor_id'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_customer_id'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_checkout_id'), table_name='marketplace_orders')
    op.drop_table('marketplace_orders')
    op.drop_index(op.f('ix_marketplace_checkouts_status'), table_name='marketplace_checkouts')
    op.drop_index(op.f('ix_marketplace_checkouts_customer_id'), table_name='marketplace_checkouts')
    op.drop_index(op.f('ix_marketplace_checkouts_checkout_number'), table_name='marketplace_checkouts')
    op.drop_table('marketplace_checkouts')
    op.drop_index(op.f('ix_marketplace_carts_customer_id'), table_name='marketplace_carts')
    op.drop_table('marketplace_carts')
    # ### end Alembic commands ###
