"""add marketplace foundation

Revision ID: 202484fa3a6f
Revises: 7852a266b631
Create Date: 2026-09-10 16:09:43.599342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202484fa3a6f'
down_revision: Union[str, Sequence[str], None] = '7852a266b631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_listing_images',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_marketplace_listing_images_listing_id_marketplace_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_listing_images'))
    )
    op.create_index(op.f('ix_marketplace_listing_images_listing_id'), 'marketplace_listing_images', ['listing_id'], unique=False)
    op.alter_column('marketplace_listings', 'slug',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('marketplace_services', 'service_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_services', sa.Column('service_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('marketplace_listings', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_index(op.f('ix_marketplace_listing_images_listing_id'), table_name='marketplace_listing_images')
    op.drop_table('marketplace_listing_images')
    # ### end Alembic commands ###
