"""add academic templates updated

Revision ID: 239ccc83f005
Revises: de97bbcdad6e
Create Date: 2026-07-09 11:14:33.238033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239ccc83f005'
down_revision: Union[str, Sequence[str], None] = 'de97bbcdad6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    # ### end Alembic commands ###
