"""add payout order and transfer reference

Revision ID: 449da4827056
Revises: 1fd43523828b
Create Date: 2026-09-22 10:58:02.640284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '449da4827056'
down_revision: Union[str, Sequence[str], None] = '1fd43523828b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_payouts', sa.Column('order_id', sa.UUID(), nullable=False))
    op.add_column('marketplace_payouts', sa.Column('reference', sa.String(length=255), nullable=False))
    op.alter_column('marketplace_payouts', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('marketplace_payouts', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('marketplace_payouts', 'bank_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('marketplace_payouts', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('marketplace_payouts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='payoutstatus'),
               nullable=False)
    op.create_index(op.f('ix_marketplace_payouts_order_id'), 'marketplace_payouts', ['order_id'], unique=True)
    op.create_index(op.f('ix_marketplace_payouts_reference'), 'marketplace_payouts', ['reference'], unique=True)
    op.create_index(op.f('ix_marketplace_payouts_status'), 'marketplace_payouts', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_payouts_transfer_code'), 'marketplace_payouts', ['transfer_code'], unique=True)
    op.create_index(op.f('ix_marketplace_payouts_vendor_id'), 'marketplace_payouts', ['vendor_id'], unique=False)
    op.drop_constraint(op.f('fk_marketplace_payouts_vendor_id_marketplace_vendors'), 'marketplace_payouts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_marketplace_payouts_order_id_marketplace_orders'), 'marketplace_payouts', 'marketplace_orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_marketplace_payouts_vendor_id_marketplace_vendors'), 'marketplace_payouts', 'marketplace_vendors', ['vendor_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_marketplace_payouts_vendor_id_marketplace_vendors'), 'marketplace_payouts', type_='foreignkey')
    op.drop_constraint(op.f('fk_marketplace_payouts_order_id_marketplace_orders'), 'marketplace_payouts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_marketplace_payouts_vendor_id_marketplace_vendors'), 'marketplace_payouts', 'marketplace_vendors', ['vendor_id'], ['id'])
    op.drop_index(op.f('ix_marketplace_payouts_vendor_id'), table_name='marketplace_payouts')
    op.drop_index(op.f('ix_marketplace_payouts_transfer_code'), table_name='marketplace_payouts')
    op.drop_index(op.f('ix_marketplace_payouts_status'), table_name='marketplace_payouts')
    op.drop_index(op.f('ix_marketplace_payouts_reference'), table_name='marketplace_payouts')
    op.drop_index(op.f('ix_marketplace_payouts_order_id'), table_name='marketplace_payouts')
    op.alter_column('marketplace_payouts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='payoutstatus'),
               nullable=True)
    op.alter_column('marketplace_payouts', 'account_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('marketplace_payouts', 'bank_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('marketplace_payouts', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('marketplace_payouts', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('marketplace_payouts', 'reference')
    op.drop_column('marketplace_payouts', 'order_id')
    # ### end Alembic commands ###
