"""add stock restored to marketplace checkout

Revision ID: 577a6af92858
Revises: 449da4827056
Create Date: 2026-09-22 11:15:25.346195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577a6af92858'
down_revision: Union[str, Sequence[str], None] = '449da4827056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_checkouts', sa.Column('stock_restored', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_checkouts', 'stock_restored')
    # ### end Alembic commands ###
