"""rename template_class_id to class_template_id

Revision ID: 57b2f52ec5d9
Revises: 
Create Date: 2026-07-30 10:54:30.693204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b2f52ec5d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_academic_periods',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_academic_periods_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_school_academic_periods_session_id_academic_sessions')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_school_academic_periods_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_academic_periods'))
    )
    op.create_index(op.f('ix_school_academic_periods_school_id'), 'school_academic_periods', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_academic_periods_session_id'), 'school_academic_periods', ['session_id'], unique=False)
    op.create_index(op.f('ix_school_academic_periods_term_id'), 'school_academic_periods', ['term_id'], unique=False)
    op.create_table('lesson_alf',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('independent_reading', sa.Text(), nullable=True),
    sa.Column('mini_lesson', sa.Text(), nullable=True),
    sa.Column('case_study', sa.Text(), nullable=True),
    sa.Column('project_based_learning', sa.Text(), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_alf_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_alf')),
    sa.UniqueConstraint('lesson_id', name=op.f('uq_lesson_alf_lesson_id'))
    )
    op.drop_index(op.f('ix_academic_sessions_school_id'), table_name='academic_sessions')
    op.create_index(op.f('ix_academic_sessions_name'), 'academic_sessions', ['name'], unique=True)
    op.drop_constraint(op.f('fk_academic_sessions_school_id_schools'), 'academic_sessions', type_='foreignkey')
    op.drop_column('academic_sessions', 'school_id')
    op.add_column('cbt_attempts', sa.Column('current_question_index', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_exam_student_attempt', 'cbt_attempts', ['exam_id', 'student_id'])
    op.add_column('lessons', sa.Column('class_template_id', sa.UUID(), nullable=False))
    op.add_column('lessons', sa.Column('subject_template_id', sa.UUID(), nullable=False))
    op.add_column('lessons', sa.Column('week_number', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('lesson_day', sa.String(length=20), nullable=False))
    op.add_column('lessons', sa.Column('teacher_notes', sa.Text(), nullable=True))
    op.alter_column('lessons', 'objectives',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('fk_lessons_class_id_classes'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('fk_lessons_subject_id_subjects'), 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lessons_subject_template_id_subject_templates'), 'lessons', 'subject_templates', ['subject_template_id'], ['id'])
    op.create_foreign_key(op.f('fk_lessons_class_template_id_class_templates'), 'lessons', 'class_templates', ['class_template_id'], ['id'])
    op.drop_column('lessons', 'subject_id')
    op.drop_column('lessons', 'class_id')
    op.add_column('terms', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_terms_school_id'), table_name='terms')
    op.create_index(op.f('ix_terms_name'), 'terms', ['name'], unique=True)
    op.drop_constraint(op.f('fk_terms_session_id_academic_sessions'), 'terms', type_='foreignkey')
    op.drop_constraint(op.f('fk_terms_school_id_schools'), 'terms', type_='foreignkey')
    op.drop_column('terms', 'end_date')
    op.drop_column('terms', 'school_id')
    op.drop_column('terms', 'session_id')
    op.drop_column('terms', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('terms', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('terms', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('terms', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_terms_school_id_schools'), 'terms', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_terms_session_id_academic_sessions'), 'terms', 'academic_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_terms_name'), table_name='terms')
    op.create_index(op.f('ix_terms_school_id'), 'terms', ['school_id'], unique=False)
    op.drop_column('terms', 'sort_order')
    op.add_column('lessons', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_lessons_class_template_id_class_templates'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('fk_lessons_subject_template_id_subject_templates'), 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lessons_subject_id_subjects'), 'lessons', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('fk_lessons_class_id_classes'), 'lessons', 'classes', ['class_id'], ['id'])
    op.alter_column('lessons', 'objectives',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('lessons', 'teacher_notes')
    op.drop_column('lessons', 'lesson_day')
    op.drop_column('lessons', 'week_number')
    op.drop_column('lessons', 'subject_template_id')
    op.drop_column('lessons', 'class_template_id')
    op.drop_constraint('uq_exam_student_attempt', 'cbt_attempts', type_='unique')
    op.drop_column('cbt_attempts', 'current_question_index')
    op.add_column('academic_sessions', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_academic_sessions_school_id_schools'), 'academic_sessions', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_academic_sessions_name'), table_name='academic_sessions')
    op.create_index(op.f('ix_academic_sessions_school_id'), 'academic_sessions', ['school_id'], unique=False)
    op.drop_table('lesson_alf')
    op.drop_index(op.f('ix_school_academic_periods_term_id'), table_name='school_academic_periods')
    op.drop_index(op.f('ix_school_academic_periods_session_id'), table_name='school_academic_periods')
    op.drop_index(op.f('ix_school_academic_periods_school_id'), table_name='school_academic_periods')
    op.drop_table('school_academic_periods')
    # ### end Alembic commands ###
