"""add model AdmissionEnquiry

Revision ID: 62da2b37dfb0
Revises: c96ed1d3dbe8
Create Date: 2026-09-03 06:30:47.041905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62da2b37dfb0'
down_revision: Union[str, Sequence[str], None] = 'c96ed1d3dbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_enquiries',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=False),
    sa.Column('parent_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('student_class', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'VISIT_SCHEDULED', 'CONVERTED', 'CLOSED', name='admissionenquirystatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['school_admissions.id'], name=op.f('fk_admission_enquiries_admission_id_school_admissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_admission_enquiries_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_enquiries'))
    )
    op.create_index(op.f('ix_admission_enquiries_admission_id'), 'admission_enquiries', ['admission_id'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_email'), 'admission_enquiries', ['email'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_phone'), 'admission_enquiries', ['phone'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_school_id'), 'admission_enquiries', ['school_id'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_status'), 'admission_enquiries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_enquiries_status'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_school_id'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_phone'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_email'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_admission_id'), table_name='admission_enquiries')
    op.drop_table('admission_enquiries')
    # ### end Alembic commands ###
