"""add academic templates

Revision ID: 706073a9a773
Revises: 28675bb5e19b
Create Date: 2026-07-07 11:10:47.961233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706073a9a773'
down_revision: Union[str, Sequence[str], None] = '28675bb5e19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_templates'))
    )
    op.create_index(op.f('ix_class_templates_level'), 'class_templates', ['level'], unique=False)
    op.create_index(op.f('ix_class_templates_name'), 'class_templates', ['name'], unique=True)
    op.create_table('subject_templates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_templates'))
    )
    op.create_index(op.f('ix_subject_templates_level'), 'subject_templates', ['level'], unique=False)
    op.create_index(op.f('ix_subject_templates_name'), 'subject_templates', ['name'], unique=True)
    op.add_column('class_subjects', sa.Column('school_id', sa.UUID(), nullable=True))
    op.alter_column('class_subjects', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('class_subjects', 'subject_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_class_subjects_school_id'), 'class_subjects', ['school_id'], unique=False)
    op.create_foreign_key(op.f('fk_class_subjects_school_id_schools'), 'class_subjects', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.add_column('classes', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_classes_level'), 'classes', ['level'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_constraint(op.f('fk_subjects_school_id_schools'), 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_subjects_school_id_schools'), 'subjects', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_level'), table_name='classes')
    op.drop_column('classes', 'sort_order')
    op.drop_constraint(op.f('fk_class_subjects_school_id_schools'), 'class_subjects', type_='foreignkey')
    op.drop_index(op.f('ix_class_subjects_school_id'), table_name='class_subjects')
    op.alter_column('class_subjects', 'subject_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('class_subjects', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('class_subjects', 'school_id')
    op.drop_index(op.f('ix_subject_templates_name'), table_name='subject_templates')
    op.drop_index(op.f('ix_subject_templates_level'), table_name='subject_templates')
    op.drop_table('subject_templates')
    op.drop_index(op.f('ix_class_templates_name'), table_name='class_templates')
    op.drop_index(op.f('ix_class_templates_level'), table_name='class_templates')
    op.drop_table('class_templates')
    # ### end Alembic commands ###
