"""add cbt

Revision ID: 748892090294
Revises: a57cb37e8635
Create Date: 2026-07-18 12:56:28.431962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748892090294'
down_revision: Union[str, Sequence[str], None] = 'a57cb37e8635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cbt_exams', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cbt_exams', 'is_published')
    # ### end Alembic commands ###
