"""add marketplace foundation

Revision ID: 7852a266b631
Revises: 
Create Date: 2026-09-10 15:45:52.256898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7852a266b631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_marketplace_categories_name'))
    )
    op.create_index(op.f('ix_marketplace_categories_is_active'), 'marketplace_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketplace_categories_slug'), 'marketplace_categories', ['slug'], unique=True)
    op.create_table('admission_enquiries',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('admission_id', sa.UUID(), nullable=False),
    sa.Column('parent_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('student_class', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'VISIT_SCHEDULED', 'CONVERTED', 'CLOSED', name='admissionenquirystatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['school_admissions.id'], name=op.f('fk_admission_enquiries_admission_id_school_admissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_admission_enquiries_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_enquiries'))
    )
    op.create_index(op.f('ix_admission_enquiries_admission_id'), 'admission_enquiries', ['admission_id'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_email'), 'admission_enquiries', ['email'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_phone'), 'admission_enquiries', ['phone'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_school_id'), 'admission_enquiries', ['school_id'], unique=False)
    op.create_index(op.f('ix_admission_enquiries_status'), 'admission_enquiries', ['status'], unique=False)
    op.create_table('marketplace_vendors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor_type', sa.Enum('INDIVIDUAL', 'BUSINESS', name='vendor_type'), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('public_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='vendor_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_marketplace_vendors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_vendors'))
    )
    op.create_index(op.f('ix_marketplace_vendors_slug'), 'marketplace_vendors', ['slug'], unique=True)
    op.create_index(op.f('ix_marketplace_vendors_status'), 'marketplace_vendors', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_vendors_user_id'), 'marketplace_vendors', ['user_id'], unique=True)
    op.create_table('marketplace_listings',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('listing_type', sa.Enum('PHYSICAL', 'SERVICE', 'DIGITAL', name='listing_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='listing_status'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id'], name=op.f('fk_marketplace_listings_category_id_marketplace_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketplace_vendors.id'], name=op.f('fk_marketplace_listings_vendor_id_marketplace_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_listings'))
    )
    op.create_index(op.f('ix_marketplace_listings_category_id'), 'marketplace_listings', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_listing_type'), 'marketplace_listings', ['listing_type'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_slug'), 'marketplace_listings', ['slug'], unique=True)
    op.create_index(op.f('ix_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_vendor_id'), 'marketplace_listings', ['vendor_id'], unique=False)
    op.create_table('marketplace_digital_products',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_marketplace_digital_products_listing_id_marketplace_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_digital_products'))
    )
    op.create_index(op.f('ix_marketplace_digital_products_listing_id'), 'marketplace_digital_products', ['listing_id'], unique=True)
    op.create_table('marketplace_physical_products',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimensions', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_marketplace_physical_products_listing_id_marketplace_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_physical_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_marketplace_physical_products_sku'))
    )
    op.create_index(op.f('ix_marketplace_physical_products_listing_id'), 'marketplace_physical_products', ['listing_id'], unique=True)
    op.create_table('marketplace_services',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('pricing_model', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_marketplace_services_listing_id_marketplace_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_services'))
    )
    op.create_index(op.f('ix_marketplace_services_listing_id'), 'marketplace_services', ['listing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_services_listing_id'), table_name='marketplace_services')
    op.drop_table('marketplace_services')
    op.drop_index(op.f('ix_marketplace_physical_products_listing_id'), table_name='marketplace_physical_products')
    op.drop_table('marketplace_physical_products')
    op.drop_index(op.f('ix_marketplace_digital_products_listing_id'), table_name='marketplace_digital_products')
    op.drop_table('marketplace_digital_products')
    op.drop_index(op.f('ix_marketplace_listings_vendor_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_slug'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_listing_type'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_category_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_marketplace_vendors_user_id'), table_name='marketplace_vendors')
    op.drop_index(op.f('ix_marketplace_vendors_status'), table_name='marketplace_vendors')
    op.drop_index(op.f('ix_marketplace_vendors_slug'), table_name='marketplace_vendors')
    op.drop_table('marketplace_vendors')
    op.drop_index(op.f('ix_admission_enquiries_status'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_school_id'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_phone'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_email'), table_name='admission_enquiries')
    op.drop_index(op.f('ix_admission_enquiries_admission_id'), table_name='admission_enquiries')
    op.drop_table('admission_enquiries')
    op.drop_index(op.f('ix_marketplace_categories_slug'), table_name='marketplace_categories')
    op.drop_index(op.f('ix_marketplace_categories_is_active'), table_name='marketplace_categories')
    op.drop_table('marketplace_categories')
    # ### end Alembic commands ###
