"""add migration

Revision ID: 7fc511cdb103
Revises: 91caf39f49fc
Create Date: 2026-08-20 16:24:14.564267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc511cdb103'
down_revision: Union[str, Sequence[str], None] = '91caf39f49fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'lesson_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lesson_day', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
