"""add cbt

Revision ID: a57cb37e8635
Revises: 
Create Date: 2026-07-17 16:30:47.503828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57cb37e8635'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbt_exams',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('pass_mark', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='examstatus'), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('allow_review', sa.Boolean(), nullable=False),
    sa.Column('show_result_immediately', sa.Boolean(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_cbt_exams_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_cbt_exams_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_cbt_exams_session_id_academic_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_cbt_exams_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_cbt_exams_term_id_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_exams'))
    )
    op.create_index('ix_cbt_exam_class_subject', 'cbt_exams', ['class_id', 'subject_id'], unique=False)
    op.create_index('ix_cbt_exam_session_term', 'cbt_exams', ['session_id', 'term_id'], unique=False)
    op.create_index(op.f('ix_cbt_exams_class_id'), 'cbt_exams', ['class_id'], unique=False)
    op.create_index(op.f('ix_cbt_exams_school_id'), 'cbt_exams', ['school_id'], unique=False)
    op.create_index(op.f('ix_cbt_exams_session_id'), 'cbt_exams', ['session_id'], unique=False)
    op.create_index(op.f('ix_cbt_exams_subject_id'), 'cbt_exams', ['subject_id'], unique=False)
    op.create_index(op.f('ix_cbt_exams_term_id'), 'cbt_exams', ['term_id'], unique=False)
    op.create_table('cbt_attempts',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_taken', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED', name='attemptstatus'), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['cbt_exams.id'], name=op.f('fk_cbt_attempts_exam_id_cbt_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_cbt_attempts_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_cbt_attempts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_attempts'))
    )
    op.create_index(op.f('ix_cbt_attempts_exam_id'), 'cbt_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_cbt_attempts_school_id'), 'cbt_attempts', ['school_id'], unique=False)
    op.create_index(op.f('ix_cbt_attempts_student_id'), 'cbt_attempts', ['student_id'], unique=False)
    op.create_index('ix_exam_student_attempt', 'cbt_attempts', ['exam_id', 'student_id'], unique=False)
    op.create_table('cbt_questions',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('OBJECTIVE', 'TRUE_FALSE', name='questiontype'), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['cbt_exams.id'], name=op.f('fk_cbt_questions_exam_id_cbt_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_questions'))
    )
    op.create_index(op.f('ix_cbt_questions_exam_id'), 'cbt_questions', ['exam_id'], unique=False)
    op.create_index('ix_exam_question_order', 'cbt_questions', ['exam_id', 'question_order'], unique=False)
    op.create_table('cbt_question_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_label', sa.String(length=5), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('option_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['cbt_questions.id'], name=op.f('fk_cbt_question_options_question_id_cbt_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_question_options'))
    )
    op.create_index(op.f('ix_cbt_question_options_question_id'), 'cbt_question_options', ['question_id'], unique=False)
    op.create_index('ix_question_option_order', 'cbt_question_options', ['question_id', 'option_order'], unique=False)
    op.create_table('cbt_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('marks_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['cbt_attempts.id'], name=op.f('fk_cbt_answers_attempt_id_cbt_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['cbt_questions.id'], name=op.f('fk_cbt_answers_question_id_cbt_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['cbt_question_options.id'], name=op.f('fk_cbt_answers_selected_option_id_cbt_question_options'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_answers'))
    )
    op.create_index('ix_attempt_question', 'cbt_answers', ['attempt_id', 'question_id'], unique=True)
    op.create_index(op.f('ix_cbt_answers_attempt_id'), 'cbt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_cbt_answers_question_id'), 'cbt_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_cbt_answers_selected_option_id'), 'cbt_answers', ['selected_option_id'], unique=False)
    op.alter_column('subjects', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_cbt_answers_selected_option_id'), table_name='cbt_answers')
    op.drop_index(op.f('ix_cbt_answers_question_id'), table_name='cbt_answers')
    op.drop_index(op.f('ix_cbt_answers_attempt_id'), table_name='cbt_answers')
    op.drop_index('ix_attempt_question', table_name='cbt_answers')
    op.drop_table('cbt_answers')
    op.drop_index('ix_question_option_order', table_name='cbt_question_options')
    op.drop_index(op.f('ix_cbt_question_options_question_id'), table_name='cbt_question_options')
    op.drop_table('cbt_question_options')
    op.drop_index('ix_exam_question_order', table_name='cbt_questions')
    op.drop_index(op.f('ix_cbt_questions_exam_id'), table_name='cbt_questions')
    op.drop_table('cbt_questions')
    op.drop_index('ix_exam_student_attempt', table_name='cbt_attempts')
    op.drop_index(op.f('ix_cbt_attempts_student_id'), table_name='cbt_attempts')
    op.drop_index(op.f('ix_cbt_attempts_school_id'), table_name='cbt_attempts')
    op.drop_index(op.f('ix_cbt_attempts_exam_id'), table_name='cbt_attempts')
    op.drop_table('cbt_attempts')
    op.drop_index(op.f('ix_cbt_exams_term_id'), table_name='cbt_exams')
    op.drop_index(op.f('ix_cbt_exams_subject_id'), table_name='cbt_exams')
    op.drop_index(op.f('ix_cbt_exams_session_id'), table_name='cbt_exams')
    op.drop_index(op.f('ix_cbt_exams_school_id'), table_name='cbt_exams')
    op.drop_index(op.f('ix_cbt_exams_class_id'), table_name='cbt_exams')
    op.drop_index('ix_cbt_exam_session_term', table_name='cbt_exams')
    op.drop_index('ix_cbt_exam_class_subject', table_name='cbt_exams')
    op.drop_table('cbt_exams')
    # ### end Alembic commands ###
