"""add migration

Revision ID: c96ed1d3dbe8
Revises: de8177961ea3
Create Date: 2026-08-28 04:05:47.116395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96ed1d3dbe8'
down_revision: Union[str, Sequence[str], None] = 'de8177961ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_admissions',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('NURSERY', 'PRIMARY', 'JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'TRANSFER', name='admissioncategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('application_fee', sa.String(length=100), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('brochure_url', sa.String(length=500), nullable=True),
    sa.Column('brochure_public_id', sa.String(length=255), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_admissions_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_admissions'))
    )
    op.create_index(op.f('ix_school_admissions_category'), 'school_admissions', ['category'], unique=False)
    op.create_index(op.f('ix_school_admissions_is_open'), 'school_admissions', ['is_open'], unique=False)
    op.create_index(op.f('ix_school_admissions_school_id'), 'school_admissions', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_admissions_session_name'), 'school_admissions', ['session_name'], unique=False)
    op.create_table('school_facilities',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_facilities_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_facilities'))
    )
    op.create_index(op.f('ix_school_facilities_school_id'), 'school_facilities', ['school_id'], unique=False)
    op.create_table('school_gallery',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('CAMPUS', 'CLASSROOM', 'LABORATORY', 'LIBRARY', 'SPORTS', 'EVENT', 'STAFF', 'OTHER', name='gallerycategory'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_gallery_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_gallery'))
    )
    op.create_index(op.f('ix_school_gallery_public_id'), 'school_gallery', ['public_id'], unique=False)
    op.create_index(op.f('ix_school_gallery_school_id'), 'school_gallery', ['school_id'], unique=False)
    op.create_table('school_programs',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_programs_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_programs'))
    )
    op.create_index(op.f('ix_school_programs_school_id'), 'school_programs', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_programs_school_id'), table_name='school_programs')
    op.drop_table('school_programs')
    op.drop_index(op.f('ix_school_gallery_school_id'), table_name='school_gallery')
    op.drop_index(op.f('ix_school_gallery_public_id'), table_name='school_gallery')
    op.drop_table('school_gallery')
    op.drop_index(op.f('ix_school_facilities_school_id'), table_name='school_facilities')
    op.drop_table('school_facilities')
    op.drop_index(op.f('ix_school_admissions_session_name'), table_name='school_admissions')
    op.drop_index(op.f('ix_school_admissions_school_id'), table_name='school_admissions')
    op.drop_index(op.f('ix_school_admissions_is_open'), table_name='school_admissions')
    op.drop_index(op.f('ix_school_admissions_category'), table_name='school_admissions')
    op.drop_table('school_admissions')
    # ### end Alembic commands ###
