"""add school directory fields

Revision ID: cd3bb2a2386f
Revises: dd26f835b96c
Create Date: 2026-08-18 17:43:12.007215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3bb2a2386f'
down_revision: Union[str, Sequence[str], None] = 'dd26f835b96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('school_type', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('ownership_type', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('is_directory_visible', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('is_directory_verified', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('is_directory_featured', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('directory_cover_image', sa.String(length=500), nullable=True))
    op.alter_column('schools', 'logo_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_schools_city'), 'schools', ['city'], unique=False)
    op.create_index(op.f('ix_schools_is_directory_featured'), 'schools', ['is_directory_featured'], unique=False)
    op.create_index(op.f('ix_schools_is_directory_verified'), 'schools', ['is_directory_verified'], unique=False)
    op.create_index(op.f('ix_schools_is_directory_visible'), 'schools', ['is_directory_visible'], unique=False)
    op.create_index(op.f('ix_schools_ownership_type'), 'schools', ['ownership_type'], unique=False)
    op.create_index(op.f('ix_schools_school_type'), 'schools', ['school_type'], unique=False)
    op.create_index(op.f('ix_schools_state'), 'schools', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_state'), table_name='schools')
    op.drop_index(op.f('ix_schools_school_type'), table_name='schools')
    op.drop_index(op.f('ix_schools_ownership_type'), table_name='schools')
    op.drop_index(op.f('ix_schools_is_directory_visible'), table_name='schools')
    op.drop_index(op.f('ix_schools_is_directory_verified'), table_name='schools')
    op.drop_index(op.f('ix_schools_is_directory_featured'), table_name='schools')
    op.drop_index(op.f('ix_schools_city'), table_name='schools')
    op.alter_column('schools', 'logo_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('schools', 'directory_cover_image')
    op.drop_column('schools', 'is_directory_featured')
    op.drop_column('schools', 'is_directory_verified')
    op.drop_column('schools', 'is_directory_visible')
    op.drop_column('schools', 'founded_year')
    op.drop_column('schools', 'ownership_type')
    op.drop_column('schools', 'school_type')
    op.drop_column('schools', 'city')
    # ### end Alembic commands ###
