"""add alf durations

Revision ID: dd26f835b96c
Revises: 
Create Date: 2026-08-11 13:55:29.244782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd26f835b96c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_alf', sa.Column('independent_reading_duration', sa.Integer(), nullable=True))
    op.add_column('lesson_alf', sa.Column('mini_lesson_duration', sa.Integer(), nullable=True))
    op.add_column('lesson_alf', sa.Column('case_study_duration', sa.Integer(), nullable=True))
    op.add_column('lesson_alf', sa.Column('project_based_learning_duration', sa.Integer(), nullable=True))
    op.add_column('lesson_alf', sa.Column('evaluation_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_alf', 'evaluation_duration')
    op.drop_column('lesson_alf', 'project_based_learning_duration')
    op.drop_column('lesson_alf', 'case_study_duration')
    op.drop_column('lesson_alf', 'mini_lesson_duration')
    op.drop_column('lesson_alf', 'independent_reading_duration')
    # ### end Alembic commands ###
