"""add academic templates updated

Revision ID: de97bbcdad6e
Revises: 706073a9a773
Create Date: 2026-07-08 12:19:37.448692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de97bbcdad6e'
down_revision: Union[str, Sequence[str], None] = '706073a9a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_templates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_templates'))
    )
    op.create_index(op.f('ix_academic_templates_name'), 'academic_templates', ['name'], unique=True)
    op.create_table('template_class_subjects',
    sa.Column('class_template_id', sa.UUID(), nullable=False),
    sa.Column('subject_template_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_template_id'], ['class_templates.id'], name=op.f('fk_template_class_subjects_class_template_id_class_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_template_id'], ['subject_templates.id'], name=op.f('fk_template_class_subjects_subject_template_id_subject_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_class_subjects')),
    sa.UniqueConstraint('class_template_id', 'subject_template_id', name='uq_template_class_subject')
    )
    op.create_index(op.f('ix_template_class_subjects_class_template_id'), 'template_class_subjects', ['class_template_id'], unique=False)
    op.create_index(op.f('ix_template_class_subjects_subject_template_id'), 'template_class_subjects', ['subject_template_id'], unique=False)
    op.add_column('class_templates', sa.Column('academic_template_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_class_templates_name'), table_name='class_templates')
    op.create_index(op.f('ix_class_templates_academic_template_id'), 'class_templates', ['academic_template_id'], unique=False)
    op.create_foreign_key(op.f('fk_class_templates_academic_template_id_academic_templates'), 'class_templates', 'academic_templates', ['academic_template_id'], ['id'], ondelete='CASCADE')
    op.add_column('classes', sa.Column('template_class_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_classes_template_class_id_class_templates'), 'classes', 'class_templates', ['template_class_id'], ['id'])
    op.add_column('schools', sa.Column('academic_setup_completed', sa.Boolean(), nullable=True))
    op.add_column('subject_templates', sa.Column('academic_template_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_subject_templates_level'), table_name='subject_templates')
    op.drop_index(op.f('ix_subject_templates_name'), table_name='subject_templates')
    op.create_index(op.f('ix_subject_templates_academic_template_id'), 'subject_templates', ['academic_template_id'], unique=False)
    op.create_foreign_key(op.f('fk_subject_templates_academic_template_id_academic_templates'), 'subject_templates', 'academic_templates', ['academic_template_id'], ['id'], ondelete='CASCADE')
    op.add_column('subjects', sa.Column('template_subject_id', sa.UUID(), nullable=True))
    op.add_column('subjects', sa.Column('school_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_foreign_key(op.f('fk_subjects_template_subject_id_subject_templates'), 'subjects', 'subject_templates', ['template_subject_id'], ['id'])
    op.create_foreign_key(op.f('fk_subjects_school_id_schools'), 'subjects', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subjects_school_id_schools'), 'subjects', type_='foreignkey')
    op.drop_constraint(op.f('fk_subjects_template_subject_id_subject_templates'), 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_column('subjects', 'school_id')
    op.drop_column('subjects', 'template_subject_id')
    op.drop_constraint(op.f('fk_subject_templates_academic_template_id_academic_templates'), 'subject_templates', type_='foreignkey')
    op.drop_index(op.f('ix_subject_templates_academic_template_id'), table_name='subject_templates')
    op.create_index(op.f('ix_subject_templates_name'), 'subject_templates', ['name'], unique=True)
    op.create_index(op.f('ix_subject_templates_level'), 'subject_templates', ['level'], unique=False)
    op.drop_column('subject_templates', 'academic_template_id')
    op.drop_column('schools', 'academic_setup_completed')
    op.drop_constraint(op.f('fk_classes_template_class_id_class_templates'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'template_class_id')
    op.drop_constraint(op.f('fk_class_templates_academic_template_id_academic_templates'), 'class_templates', type_='foreignkey')
    op.drop_index(op.f('ix_class_templates_academic_template_id'), table_name='class_templates')
    op.create_index(op.f('ix_class_templates_name'), 'class_templates', ['name'], unique=True)
    op.drop_column('class_templates', 'academic_template_id')
    op.drop_index(op.f('ix_template_class_subjects_subject_template_id'), table_name='template_class_subjects')
    op.drop_index(op.f('ix_template_class_subjects_class_template_id'), table_name='template_class_subjects')
    op.drop_table('template_class_subjects')
    op.drop_index(op.f('ix_academic_templates_name'), table_name='academic_templates')
    op.drop_table('academic_templates')
    # ### end Alembic commands ###
