"""fix market category

Revision ID: ebc907ffb9f0
Revises: 210289b75611
Create Date: 2026-09-15 11:17:54.411975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc907ffb9f0'
down_revision: Union[str, Sequence[str], None] = '210289b75611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_attendance_records_student_id_users'), 'attendance_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attendance_records_student_id_users'), 'attendance_records', 'users', ['student_id'], ['id'])
    op.drop_constraint(op.f('fk_attendance_sheets_updated_by_users'), 'attendance_sheets', type_='foreignkey')
    op.drop_constraint(op.f('fk_attendance_sheets_marked_by_users'), 'attendance_sheets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attendance_sheets_updated_by_users'), 'attendance_sheets', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_attendance_sheets_marked_by_users'), 'attendance_sheets', 'users', ['marked_by'], ['id'])
    op.drop_constraint(op.f('fk_blog_posts_author_id_users'), 'blog_posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_blog_posts_author_id_users'), 'blog_posts', 'users', ['author_id'], ['id'])
    op.drop_constraint(op.f('fk_lessons_created_by_users'), 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lessons_created_by_users'), 'lessons', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_result_approvals_action_by_users'), 'result_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_approvals_action_by_users'), 'result_approvals', 'users', ['action_by'], ['id'])
    op.drop_constraint(op.f('fk_result_batches_created_by_users'), 'result_batches', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_batches_created_by_users'), 'result_batches', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_result_records_student_id_users'), 'result_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_records_student_id_users'), 'result_records', 'users', ['student_id'], ['id'])
    op.drop_constraint(op.f('fk_result_summaries_student_id_users'), 'result_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_summaries_student_id_users'), 'result_summaries', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_result_summaries_student_id_users'), 'result_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_summaries_student_id_users'), 'result_summaries', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_result_records_student_id_users'), 'result_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_records_student_id_users'), 'result_records', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_result_batches_created_by_users'), 'result_batches', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_batches_created_by_users'), 'result_batches', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_result_approvals_action_by_users'), 'result_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_approvals_action_by_users'), 'result_approvals', 'users', ['action_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_lessons_created_by_users'), 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lessons_created_by_users'), 'lessons', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_blog_posts_author_id_users'), 'blog_posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_blog_posts_author_id_users'), 'blog_posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_attendance_sheets_marked_by_users'), 'attendance_sheets', type_='foreignkey')
    op.drop_constraint(op.f('fk_attendance_sheets_updated_by_users'), 'attendance_sheets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attendance_sheets_marked_by_users'), 'attendance_sheets', 'users', ['marked_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_attendance_sheets_updated_by_users'), 'attendance_sheets', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_attendance_records_student_id_users'), 'attendance_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attendance_records_student_id_users'), 'attendance_records', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
